//created on: Aug 14, 2013
package com.rhc.insurance.rules

import com.rhc.insurance.Member;
import com.rhc.insurance.Policy;

import java.math.BigDecimal; 

//dialect "mvel";


rule "set BH for member"

    when
        //conditions
        $member : Member
	(
		depressionRating != null,
		anxietyRating != null,
		eatingDisorderRating != null
	)
        
        
        
    then
        //actions
       // $member.setPhysicalHealth($member.asthmaRating.add($member.diabetesRating).add($member.cardiovascularRating));
        $member.setBehavioralHealth($member.depressionRating.add($member.anxietyRating).add($member.eatingDisorderRating));
        System.out.println("fired rule " + kcontext.getRule().getName());
    

end

